EquipLevelupConfig = {
	['男魔仙器根骨向'] = {Target = "男魔仙器根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男魔仙器力量向'] = {Target = "男魔仙器力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男魔仙器敏捷向'] = {Target = "男魔仙器敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女魔仙器根骨向'] = {Target = "女魔仙器根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女魔仙器力量向'] = {Target = "女魔仙器力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女魔仙器敏捷向'] = {Target = "女魔仙器敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男人仙器根骨向'] = {Target = "男人仙器根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男人仙器力量向'] = {Target = "男人仙器力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男人仙器敏捷向'] = {Target = "男人仙器敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女人仙器根骨向'] = {Target = "女人仙器根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女人仙器力量向'] = {Target = "女人仙器力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女人仙器敏捷向'] = {Target = "女人仙器敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男鬼仙器根骨向'] = {Target = "男鬼仙器根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男鬼仙器力量向'] = {Target = "男鬼仙器力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男鬼仙器敏捷向'] = {Target = "男鬼仙器敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女鬼仙器根骨向'] = {Target = "女鬼仙器根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女鬼仙器力量向'] = {Target = "女鬼仙器力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女鬼仙器敏捷向'] = {Target = "女鬼仙器敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男仙仙器灵性向'] = {Target = "男仙仙器灵性向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男仙仙器力量向'] = {Target = "男仙仙器力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男仙仙器敏捷向'] = {Target = "男仙仙器敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女仙仙器灵性向'] = {Target = "女仙仙器灵性向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女仙仙器力量向'] = {Target = "女仙仙器力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女仙仙器敏捷向'] = {Target = "女仙仙器敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男龙仙器根骨向'] = {Target = "男龙仙器根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男龙仙器力量向'] = {Target = "男龙仙器力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男龙仙器敏捷向'] = {Target = "男龙仙器敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女龙仙器根骨向'] = {Target = "女龙仙器根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女龙仙器力量向'] = {Target = "女龙仙器力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女龙仙器敏捷向'] = {Target = "女龙仙器敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男魔仙器根骨向二阶'] = {Target = "男魔仙器根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男魔仙器力量向二阶'] = {Target = "男魔仙器力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男魔仙器敏捷向二阶'] = {Target = "男魔仙器敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女魔仙器根骨向二阶'] = {Target = "女魔仙器根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女魔仙器力量向二阶'] = {Target = "女魔仙器力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女魔仙器敏捷向二阶'] = {Target = "女魔仙器敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男人仙器根骨向二阶'] = {Target = "男人仙器根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男人仙器力量向二阶'] = {Target = "男人仙器力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男人仙器敏捷向二阶'] = {Target = "男人仙器敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女人仙器根骨向二阶'] = {Target = "女人仙器根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女人仙器力量向二阶'] = {Target = "女人仙器力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女人仙器敏捷向二阶'] = {Target = "女人仙器敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男鬼仙器根骨向二阶'] = {Target = "男鬼仙器根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男鬼仙器力量向二阶'] = {Target = "男鬼仙器力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男鬼仙器敏捷向二阶'] = {Target = "男鬼仙器敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女鬼仙器根骨向二阶'] = {Target = "女鬼仙器根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女鬼仙器力量向二阶'] = {Target = "女鬼仙器力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女鬼仙器敏捷向二阶'] = {Target = "女鬼仙器敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男仙仙器灵性向二阶'] = {Target = "男仙仙器灵性向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男仙仙器力量向二阶'] = {Target = "男仙仙器力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男仙仙器敏捷向二阶'] = {Target = "男仙仙器敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女仙仙器灵性向二阶'] = {Target = "女仙仙器灵性向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女仙仙器力量向二阶'] = {Target = "女仙仙器力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女仙仙器敏捷向二阶'] = {Target = "女仙仙器敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男龙仙器根骨向二阶'] = {Target = "男龙仙器根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男龙仙器力量向二阶'] = {Target = "男龙仙器力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男龙仙器敏捷向二阶'] = {Target = "男龙仙器敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女龙仙器根骨向二阶'] = {Target = "女龙仙器根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女龙仙器力量向二阶'] = {Target = "女龙仙器力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女龙仙器敏捷向二阶'] = {Target = "女龙仙器敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男魔仙器根骨向三阶'] = {Target = "男魔仙器根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男魔仙器力量向三阶'] = {Target = "男魔仙器力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男魔仙器敏捷向三阶'] = {Target = "男魔仙器敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女魔仙器根骨向三阶'] = {Target = "女魔仙器根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女魔仙器力量向三阶'] = {Target = "女魔仙器力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女魔仙器敏捷向三阶'] = {Target = "女魔仙器敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男人仙器根骨向三阶'] = {Target = "男人仙器根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男人仙器力量向三阶'] = {Target = "男人仙器力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男人仙器敏捷向三阶'] = {Target = "男人仙器敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女人仙器根骨向三阶'] = {Target = "女人仙器根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女人仙器力量向三阶'] = {Target = "女人仙器力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女人仙器敏捷向三阶'] = {Target = "女人仙器敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男鬼仙器根骨向三阶'] = {Target = "男鬼仙器根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男鬼仙器力量向三阶'] = {Target = "男鬼仙器力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男鬼仙器敏捷向三阶'] = {Target = "男鬼仙器敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女鬼仙器根骨向三阶'] = {Target = "女鬼仙器根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女鬼仙器力量向三阶'] = {Target = "女鬼仙器力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女鬼仙器敏捷向三阶'] = {Target = "女鬼仙器敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男仙仙器灵性向三阶'] = {Target = "男仙仙器灵性向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男仙仙器力量向三阶'] = {Target = "男仙仙器力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男仙仙器敏捷向三阶'] = {Target = "男仙仙器敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女仙仙器灵性向三阶'] = {Target = "女仙仙器灵性向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女仙仙器力量向三阶'] = {Target = "女仙仙器力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女仙仙器敏捷向三阶'] = {Target = "女仙仙器敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男龙仙器根骨向三阶'] = {Target = "男龙仙器根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男龙仙器力量向三阶'] = {Target = "男龙仙器力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男龙仙器敏捷向三阶'] = {Target = "男龙仙器敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女龙仙器根骨向三阶'] = {Target = "女龙仙器根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女龙仙器力量向三阶'] = {Target = "女龙仙器力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女龙仙器敏捷向三阶'] = {Target = "女龙仙器敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男魔仙器根骨向四阶'] = {Target = "男魔仙器根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男魔仙器力量向四阶'] = {Target = "男魔仙器力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男魔仙器敏捷向四阶'] = {Target = "男魔仙器敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女魔仙器根骨向四阶'] = {Target = "女魔仙器根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女魔仙器力量向四阶'] = {Target = "女魔仙器力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女魔仙器敏捷向四阶'] = {Target = "女魔仙器敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男人仙器根骨向四阶'] = {Target = "男人仙器根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男人仙器力量向四阶'] = {Target = "男人仙器力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男人仙器敏捷向四阶'] = {Target = "男人仙器敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女人仙器根骨向四阶'] = {Target = "女人仙器根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女人仙器力量向四阶'] = {Target = "女人仙器力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女人仙器敏捷向四阶'] = {Target = "女人仙器敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男鬼仙器根骨向四阶'] = {Target = "男鬼仙器根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男鬼仙器力量向四阶'] = {Target = "男鬼仙器力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男鬼仙器敏捷向四阶'] = {Target = "男鬼仙器敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女鬼仙器根骨向四阶'] = {Target = "女鬼仙器根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女鬼仙器力量向四阶'] = {Target = "女鬼仙器力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女鬼仙器敏捷向四阶'] = {Target = "女鬼仙器敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男仙仙器灵性向四阶'] = {Target = "男仙仙器灵性向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男仙仙器力量向四阶'] = {Target = "男仙仙器力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男仙仙器敏捷向四阶'] = {Target = "男仙仙器敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女仙仙器灵性向四阶'] = {Target = "女仙仙器灵性向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女仙仙器力量向四阶'] = {Target = "女仙仙器力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女仙仙器敏捷向四阶'] = {Target = "女仙仙器敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男龙仙器根骨向四阶'] = {Target = "男龙仙器根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男龙仙器力量向四阶'] = {Target = "男龙仙器力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男龙仙器敏捷向四阶'] = {Target = "男龙仙器敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女龙仙器根骨向四阶'] = {Target = "女龙仙器根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女龙仙器力量向四阶'] = {Target = "女龙仙器力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女龙仙器敏捷向四阶'] = {Target = "女龙仙器敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	--['男魔仙器根骨向五阶'] = {Target = "男魔仙器根骨向六阶", Materials = {"6阶仙器卷轴男魔", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男魔仙器力量向五阶'] = {Target = "男魔仙器力量向六阶", Materials = {"6阶仙器卷轴男魔", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男魔仙器敏捷向五阶'] = {Target = "男魔仙器敏捷向六阶", Materials = {"6阶仙器卷轴男魔", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女魔仙器根骨向五阶'] = {Target = "女魔仙器根骨向六阶", Materials = {"6阶仙器卷轴女魔", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女魔仙器力量向五阶'] = {Target = "女魔仙器力量向六阶", Materials = {"6阶仙器卷轴女魔", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女魔仙器敏捷向五阶'] = {Target = "女魔仙器敏捷向六阶", Materials = {"6阶仙器卷轴女魔", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男人仙器根骨向五阶'] = {Target = "男人仙器根骨向六阶", Materials = {"6阶仙器卷轴男人", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男人仙器力量向五阶'] = {Target = "男人仙器力量向六阶", Materials = {"6阶仙器卷轴男人", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男人仙器敏捷向五阶'] = {Target = "男人仙器敏捷向六阶", Materials = {"6阶仙器卷轴男人", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女人仙器根骨向五阶'] = {Target = "女人仙器根骨向六阶", Materials = {"6阶仙器卷轴女人", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女人仙器力量向五阶'] = {Target = "女人仙器力量向六阶", Materials = {"6阶仙器卷轴女人", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女人仙器敏捷向五阶'] = {Target = "女人仙器敏捷向六阶", Materials = {"6阶仙器卷轴女人", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男鬼仙器根骨向五阶'] = {Target = "男鬼仙器根骨向六阶", Materials = {"6阶仙器卷轴男鬼", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男鬼仙器力量向五阶'] = {Target = "男鬼仙器力量向六阶", Materials = {"6阶仙器卷轴男鬼", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男鬼仙器敏捷向五阶'] = {Target = "男鬼仙器敏捷向六阶", Materials = {"6阶仙器卷轴男鬼", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女鬼仙器根骨向五阶'] = {Target = "女鬼仙器根骨向六阶", Materials = {"6阶仙器卷轴女鬼", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女鬼仙器力量向五阶'] = {Target = "女鬼仙器力量向六阶", Materials = {"6阶仙器卷轴女鬼", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女鬼仙器敏捷向五阶'] = {Target = "女鬼仙器敏捷向六阶", Materials = {"6阶仙器卷轴女鬼", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男仙仙器灵性向五阶'] = {Target = "男仙仙器灵性向六阶", Materials = {"6阶仙器卷轴男仙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男仙仙器力量向五阶'] = {Target = "男仙仙器力量向六阶", Materials = {"6阶仙器卷轴男仙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男仙仙器敏捷向五阶'] = {Target = "男仙仙器敏捷向六阶", Materials = {"6阶仙器卷轴男仙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女仙仙器灵性向五阶'] = {Target = "女仙仙器灵性向六阶", Materials = {"6阶仙器卷轴女仙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女仙仙器力量向五阶'] = {Target = "女仙仙器力量向六阶", Materials = {"6阶仙器卷轴女仙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女仙仙器敏捷向五阶'] = {Target = "女仙仙器敏捷向六阶", Materials = {"6阶仙器卷轴女仙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男龙仙器根骨向五阶'] = {Target = "男龙仙器根骨向六阶", Materials = {"6阶仙器卷轴男龙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男龙仙器力量向五阶'] = {Target = "男龙仙器力量向六阶", Materials = {"6阶仙器卷轴男龙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男龙仙器敏捷向五阶'] = {Target = "男龙仙器敏捷向六阶", Materials = {"6阶仙器卷轴男龙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女龙仙器根骨向五阶'] = {Target = "女龙仙器根骨向六阶", Materials = {"6阶仙器卷轴女龙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女龙仙器力量向五阶'] = {Target = "女龙仙器力量向六阶", Materials = {"6阶仙器卷轴女龙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女龙仙器敏捷向五阶'] = {Target = "女龙仙器敏捷向六阶", Materials = {"6阶仙器卷轴女龙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男魔仙器根骨向六阶'] = {Target = "男魔仙器根骨向七阶", Materials = {"7阶仙器卷轴男魔", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男魔仙器力量向六阶'] = {Target = "男魔仙器力量向七阶", Materials = {"7阶仙器卷轴男魔", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男魔仙器敏捷向六阶'] = {Target = "男魔仙器敏捷向七阶", Materials = {"7阶仙器卷轴男魔", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女魔仙器根骨向六阶'] = {Target = "女魔仙器根骨向七阶", Materials = {"7阶仙器卷轴女魔", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女魔仙器力量向六阶'] = {Target = "女魔仙器力量向七阶", Materials = {"7阶仙器卷轴女魔", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女魔仙器敏捷向六阶'] = {Target = "女魔仙器敏捷向七阶", Materials = {"7阶仙器卷轴女魔", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男人仙器根骨向六阶'] = {Target = "男人仙器根骨向七阶", Materials = {"7阶仙器卷轴男人", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男人仙器力量向六阶'] = {Target = "男人仙器力量向七阶", Materials = {"7阶仙器卷轴男人", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男人仙器敏捷向六阶'] = {Target = "男人仙器敏捷向七阶", Materials = {"7阶仙器卷轴男人", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女人仙器根骨向六阶'] = {Target = "女人仙器根骨向七阶", Materials = {"7阶仙器卷轴女人", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女人仙器力量向六阶'] = {Target = "女人仙器力量向七阶", Materials = {"7阶仙器卷轴女人", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女人仙器敏捷向六阶'] = {Target = "女人仙器敏捷向七阶", Materials = {"7阶仙器卷轴女人", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男鬼仙器根骨向六阶'] = {Target = "男鬼仙器根骨向七阶", Materials = {"7阶仙器卷轴男鬼", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男鬼仙器力量向六阶'] = {Target = "男鬼仙器力量向七阶", Materials = {"7阶仙器卷轴男鬼", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男鬼仙器敏捷向六阶'] = {Target = "男鬼仙器敏捷向七阶", Materials = {"7阶仙器卷轴男鬼", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女鬼仙器根骨向六阶'] = {Target = "女鬼仙器根骨向七阶", Materials = {"7阶仙器卷轴女鬼", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女鬼仙器力量向六阶'] = {Target = "女鬼仙器力量向七阶", Materials = {"7阶仙器卷轴女鬼", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女鬼仙器敏捷向六阶'] = {Target = "女鬼仙器敏捷向七阶", Materials = {"7阶仙器卷轴女鬼", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男仙仙器灵性向六阶'] = {Target = "男仙仙器灵性向七阶", Materials = {"7阶仙器卷轴男仙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男仙仙器力量向六阶'] = {Target = "男仙仙器力量向七阶", Materials = {"7阶仙器卷轴男仙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男仙仙器敏捷向六阶'] = {Target = "男仙仙器敏捷向七阶", Materials = {"7阶仙器卷轴男仙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女仙仙器灵性向六阶'] = {Target = "女仙仙器灵性向七阶", Materials = {"7阶仙器卷轴女仙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女仙仙器力量向六阶'] = {Target = "女仙仙器力量向七阶", Materials = {"7阶仙器卷轴女仙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女仙仙器敏捷向六阶'] = {Target = "女仙仙器敏捷向七阶", Materials = {"7阶仙器卷轴女仙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男龙仙器根骨向六阶'] = {Target = "男龙仙器根骨向七阶", Materials = {"7阶仙器卷轴男龙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男龙仙器力量向六阶'] = {Target = "男龙仙器力量向七阶", Materials = {"7阶仙器卷轴男龙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男龙仙器敏捷向六阶'] = {Target = "男龙仙器敏捷向七阶", Materials = {"7阶仙器卷轴男龙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女龙仙器根骨向六阶'] = {Target = "女龙仙器根骨向七阶", Materials = {"7阶仙器卷轴女龙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女龙仙器力量向六阶'] = {Target = "女龙仙器力量向七阶", Materials = {"7阶仙器卷轴女龙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女龙仙器敏捷向六阶'] = {Target = "女龙仙器敏捷向七阶", Materials = {"7阶仙器卷轴女龙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	['男魔帽子根骨向'] = {Target = "男魔帽子根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男魔帽子力量向'] = {Target = "男魔帽子力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男魔帽子敏捷向'] = {Target = "男魔帽子敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女魔帽子根骨向'] = {Target = "女魔帽子根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女魔帽子力量向'] = {Target = "女魔帽子力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女魔帽子敏捷向'] = {Target = "女魔帽子敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男人帽子根骨向'] = {Target = "男人帽子根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男人帽子力量向'] = {Target = "男人帽子力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男人帽子敏捷向'] = {Target = "男人帽子敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女人帽子根骨向'] = {Target = "女人帽子根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女人帽子力量向'] = {Target = "女人帽子力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女人帽子敏捷向'] = {Target = "女人帽子敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男鬼帽子根骨向'] = {Target = "男鬼帽子根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男鬼帽子力量向'] = {Target = "男鬼帽子力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男鬼帽子敏捷向'] = {Target = "男鬼帽子敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女鬼帽子根骨向'] = {Target = "女鬼帽子根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女鬼帽子力量向'] = {Target = "女鬼帽子力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女鬼帽子敏捷向'] = {Target = "女鬼帽子敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男仙帽子灵性向'] = {Target = "男仙帽子灵性向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男仙帽子力量向'] = {Target = "男仙帽子力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男仙帽子敏捷向'] = {Target = "男仙帽子敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女仙帽子灵性向'] = {Target = "女仙帽子灵性向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女仙帽子力量向'] = {Target = "女仙帽子力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女仙帽子敏捷向'] = {Target = "女仙帽子敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男龙帽子根骨向'] = {Target = "男龙帽子根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男龙帽子力量向'] = {Target = "男龙帽子力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男龙帽子敏捷向'] = {Target = "男龙帽子敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女龙帽子根骨向'] = {Target = "女龙帽子根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女龙帽子力量向'] = {Target = "女龙帽子力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女龙帽子敏捷向'] = {Target = "女龙帽子敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男魔帽子根骨向二阶'] = {Target = "男魔帽子根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男魔帽子力量向二阶'] = {Target = "男魔帽子力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男魔帽子敏捷向二阶'] = {Target = "男魔帽子敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女魔帽子根骨向二阶'] = {Target = "女魔帽子根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女魔帽子力量向二阶'] = {Target = "女魔帽子力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女魔帽子敏捷向二阶'] = {Target = "女魔帽子敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男人帽子根骨向二阶'] = {Target = "男人帽子根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男人帽子力量向二阶'] = {Target = "男人帽子力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男人帽子敏捷向二阶'] = {Target = "男人帽子敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女人帽子根骨向二阶'] = {Target = "女人帽子根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女人帽子力量向二阶'] = {Target = "女人帽子力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女人帽子敏捷向二阶'] = {Target = "女人帽子敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男鬼帽子根骨向二阶'] = {Target = "男鬼帽子根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男鬼帽子力量向二阶'] = {Target = "男鬼帽子力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男鬼帽子敏捷向二阶'] = {Target = "男鬼帽子敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女鬼帽子根骨向二阶'] = {Target = "女鬼帽子根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女鬼帽子力量向二阶'] = {Target = "女鬼帽子力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女鬼帽子敏捷向二阶'] = {Target = "女鬼帽子敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男仙帽子灵性向二阶'] = {Target = "男仙帽子灵性向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男仙帽子力量向二阶'] = {Target = "男仙帽子力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男仙帽子敏捷向二阶'] = {Target = "男仙帽子敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女仙帽子灵性向二阶'] = {Target = "女仙帽子灵性向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女仙帽子力量向二阶'] = {Target = "女仙帽子力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女仙帽子敏捷向二阶'] = {Target = "女仙帽子敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男龙帽子根骨向二阶'] = {Target = "男龙帽子根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男龙帽子力量向二阶'] = {Target = "男龙帽子力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男龙帽子敏捷向二阶'] = {Target = "男龙帽子敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女龙帽子根骨向二阶'] = {Target = "女龙帽子根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女龙帽子力量向二阶'] = {Target = "女龙帽子力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女龙帽子敏捷向二阶'] = {Target = "女龙帽子敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男魔帽子根骨向三阶'] = {Target = "男魔帽子根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男魔帽子力量向三阶'] = {Target = "男魔帽子力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男魔帽子敏捷向三阶'] = {Target = "男魔帽子敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女魔帽子根骨向三阶'] = {Target = "女魔帽子根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女魔帽子力量向三阶'] = {Target = "女魔帽子力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女魔帽子敏捷向三阶'] = {Target = "女魔帽子敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男人帽子根骨向三阶'] = {Target = "男人帽子根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男人帽子力量向三阶'] = {Target = "男人帽子力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男人帽子敏捷向三阶'] = {Target = "男人帽子敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女人帽子根骨向三阶'] = {Target = "女人帽子根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女人帽子力量向三阶'] = {Target = "女人帽子力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女人帽子敏捷向三阶'] = {Target = "女人帽子敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男鬼帽子根骨向三阶'] = {Target = "男鬼帽子根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男鬼帽子力量向三阶'] = {Target = "男鬼帽子力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男鬼帽子敏捷向三阶'] = {Target = "男鬼帽子敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女鬼帽子根骨向三阶'] = {Target = "女鬼帽子根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女鬼帽子力量向三阶'] = {Target = "女鬼帽子力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女鬼帽子敏捷向三阶'] = {Target = "女鬼帽子敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男仙帽子灵性向三阶'] = {Target = "男仙帽子灵性向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男仙帽子力量向三阶'] = {Target = "男仙帽子力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男仙帽子敏捷向三阶'] = {Target = "男仙帽子敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女仙帽子灵性向三阶'] = {Target = "女仙帽子灵性向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女仙帽子力量向三阶'] = {Target = "女仙帽子力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女仙帽子敏捷向三阶'] = {Target = "女仙帽子敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男龙帽子根骨向三阶'] = {Target = "男龙帽子根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男龙帽子力量向三阶'] = {Target = "男龙帽子力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男龙帽子敏捷向三阶'] = {Target = "男龙帽子敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女龙帽子根骨向三阶'] = {Target = "女龙帽子根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女龙帽子力量向三阶'] = {Target = "女龙帽子力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女龙帽子敏捷向三阶'] = {Target = "女龙帽子敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男魔帽子根骨向四阶'] = {Target = "男魔帽子根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男魔帽子力量向四阶'] = {Target = "男魔帽子力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男魔帽子敏捷向四阶'] = {Target = "男魔帽子敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女魔帽子根骨向四阶'] = {Target = "女魔帽子根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女魔帽子力量向四阶'] = {Target = "女魔帽子力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女魔帽子敏捷向四阶'] = {Target = "女魔帽子敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男人帽子根骨向四阶'] = {Target = "男人帽子根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男人帽子力量向四阶'] = {Target = "男人帽子力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男人帽子敏捷向四阶'] = {Target = "男人帽子敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女人帽子根骨向四阶'] = {Target = "女人帽子根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女人帽子力量向四阶'] = {Target = "女人帽子力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女人帽子敏捷向四阶'] = {Target = "女人帽子敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男鬼帽子根骨向四阶'] = {Target = "男鬼帽子根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男鬼帽子力量向四阶'] = {Target = "男鬼帽子力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男鬼帽子敏捷向四阶'] = {Target = "男鬼帽子敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女鬼帽子根骨向四阶'] = {Target = "女鬼帽子根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女鬼帽子力量向四阶'] = {Target = "女鬼帽子力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女鬼帽子敏捷向四阶'] = {Target = "女鬼帽子敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男仙帽子灵性向四阶'] = {Target = "男仙帽子灵性向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男仙帽子力量向四阶'] = {Target = "男仙帽子力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男仙帽子敏捷向四阶'] = {Target = "男仙帽子敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女仙帽子灵性向四阶'] = {Target = "女仙帽子灵性向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女仙帽子力量向四阶'] = {Target = "女仙帽子力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女仙帽子敏捷向四阶'] = {Target = "女仙帽子敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男龙帽子根骨向四阶'] = {Target = "男龙帽子根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男龙帽子力量向四阶'] = {Target = "男龙帽子力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男龙帽子敏捷向四阶'] = {Target = "男龙帽子敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女龙帽子根骨向四阶'] = {Target = "女龙帽子根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女龙帽子力量向四阶'] = {Target = "女龙帽子力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女龙帽子敏捷向四阶'] = {Target = "女龙帽子敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	--['男魔帽子根骨向五阶'] = {Target = "男魔帽子根骨向六阶", Materials = {"6阶仙器卷轴男魔", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男魔帽子力量向五阶'] = {Target = "男魔帽子力量向六阶", Materials = {"6阶仙器卷轴男魔", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男魔帽子敏捷向五阶'] = {Target = "男魔帽子敏捷向六阶", Materials = {"6阶仙器卷轴男魔", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女魔帽子根骨向五阶'] = {Target = "女魔帽子根骨向六阶", Materials = {"6阶仙器卷轴女魔", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女魔帽子力量向五阶'] = {Target = "女魔帽子力量向六阶", Materials = {"6阶仙器卷轴女魔", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女魔帽子敏捷向五阶'] = {Target = "女魔帽子敏捷向六阶", Materials = {"6阶仙器卷轴女魔", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男人帽子根骨向五阶'] = {Target = "男人帽子根骨向六阶", Materials = {"6阶仙器卷轴男人", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男人帽子力量向五阶'] = {Target = "男人帽子力量向六阶", Materials = {"6阶仙器卷轴男人", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男人帽子敏捷向五阶'] = {Target = "男人帽子敏捷向六阶", Materials = {"6阶仙器卷轴男人", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女人帽子根骨向五阶'] = {Target = "女人帽子根骨向六阶", Materials = {"6阶仙器卷轴女人", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女人帽子力量向五阶'] = {Target = "女人帽子力量向六阶", Materials = {"6阶仙器卷轴女人", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女人帽子敏捷向五阶'] = {Target = "女人帽子敏捷向六阶", Materials = {"6阶仙器卷轴女人", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男鬼帽子根骨向五阶'] = {Target = "男鬼帽子根骨向六阶", Materials = {"6阶仙器卷轴男鬼", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男鬼帽子力量向五阶'] = {Target = "男鬼帽子力量向六阶", Materials = {"6阶仙器卷轴男鬼", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男鬼帽子敏捷向五阶'] = {Target = "男鬼帽子敏捷向六阶", Materials = {"6阶仙器卷轴男鬼", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女鬼帽子根骨向五阶'] = {Target = "女鬼帽子根骨向六阶", Materials = {"6阶仙器卷轴女鬼", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女鬼帽子力量向五阶'] = {Target = "女鬼帽子力量向六阶", Materials = {"6阶仙器卷轴女鬼", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女鬼帽子敏捷向五阶'] = {Target = "女鬼帽子敏捷向六阶", Materials = {"6阶仙器卷轴女鬼", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男仙帽子灵性向五阶'] = {Target = "男仙帽子灵性向六阶", Materials = {"6阶仙器卷轴男仙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男仙帽子力量向五阶'] = {Target = "男仙帽子力量向六阶", Materials = {"6阶仙器卷轴男仙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男仙帽子敏捷向五阶'] = {Target = "男仙帽子敏捷向六阶", Materials = {"6阶仙器卷轴男仙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女仙帽子灵性向五阶'] = {Target = "女仙帽子灵性向六阶", Materials = {"6阶仙器卷轴女仙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女仙帽子力量向五阶'] = {Target = "女仙帽子力量向六阶", Materials = {"6阶仙器卷轴女仙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女仙帽子敏捷向五阶'] = {Target = "女仙帽子敏捷向六阶", Materials = {"6阶仙器卷轴女仙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男龙帽子根骨向五阶'] = {Target = "男龙帽子根骨向六阶", Materials = {"6阶仙器卷轴男龙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男龙帽子力量向五阶'] = {Target = "男龙帽子力量向六阶", Materials = {"6阶仙器卷轴男龙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男龙帽子敏捷向五阶'] = {Target = "男龙帽子敏捷向六阶", Materials = {"6阶仙器卷轴男龙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女龙帽子根骨向五阶'] = {Target = "女龙帽子根骨向六阶", Materials = {"6阶仙器卷轴女龙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女龙帽子力量向五阶'] = {Target = "女龙帽子力量向六阶", Materials = {"6阶仙器卷轴女龙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女龙帽子敏捷向五阶'] = {Target = "女龙帽子敏捷向六阶", Materials = {"6阶仙器卷轴女龙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男魔帽子根骨向六阶'] = {Target = "男魔帽子根骨向七阶", Materials = {"7阶仙器卷轴男魔", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男魔帽子力量向六阶'] = {Target = "男魔帽子力量向七阶", Materials = {"7阶仙器卷轴男魔", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男魔帽子敏捷向六阶'] = {Target = "男魔帽子敏捷向七阶", Materials = {"7阶仙器卷轴男魔", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女魔帽子根骨向六阶'] = {Target = "女魔帽子根骨向七阶", Materials = {"7阶仙器卷轴女魔", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女魔帽子力量向六阶'] = {Target = "女魔帽子力量向七阶", Materials = {"7阶仙器卷轴女魔", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女魔帽子敏捷向六阶'] = {Target = "女魔帽子敏捷向七阶", Materials = {"7阶仙器卷轴女魔", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男人帽子根骨向六阶'] = {Target = "男人帽子根骨向七阶", Materials = {"7阶仙器卷轴男人", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男人帽子力量向六阶'] = {Target = "男人帽子力量向七阶", Materials = {"7阶仙器卷轴男人", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男人帽子敏捷向六阶'] = {Target = "男人帽子敏捷向七阶", Materials = {"7阶仙器卷轴男人", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女人帽子根骨向六阶'] = {Target = "女人帽子根骨向七阶", Materials = {"7阶仙器卷轴女人", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女人帽子力量向六阶'] = {Target = "女人帽子力量向七阶", Materials = {"7阶仙器卷轴女人", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女人帽子敏捷向六阶'] = {Target = "女人帽子敏捷向七阶", Materials = {"7阶仙器卷轴女人", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男鬼帽子根骨向六阶'] = {Target = "男鬼帽子根骨向七阶", Materials = {"7阶仙器卷轴男鬼", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男鬼帽子力量向六阶'] = {Target = "男鬼帽子力量向七阶", Materials = {"7阶仙器卷轴男鬼", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男鬼帽子敏捷向六阶'] = {Target = "男鬼帽子敏捷向七阶", Materials = {"7阶仙器卷轴男鬼", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女鬼帽子根骨向六阶'] = {Target = "女鬼帽子根骨向七阶", Materials = {"7阶仙器卷轴女鬼", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女鬼帽子力量向六阶'] = {Target = "女鬼帽子力量向七阶", Materials = {"7阶仙器卷轴女鬼", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女鬼帽子敏捷向六阶'] = {Target = "女鬼帽子敏捷向七阶", Materials = {"7阶仙器卷轴女鬼", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男仙帽子灵性向六阶'] = {Target = "男仙帽子灵性向七阶", Materials = {"7阶仙器卷轴男仙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男仙帽子力量向六阶'] = {Target = "男仙帽子力量向七阶", Materials = {"7阶仙器卷轴男仙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男仙帽子敏捷向六阶'] = {Target = "男仙帽子敏捷向七阶", Materials = {"7阶仙器卷轴男仙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女仙帽子灵性向六阶'] = {Target = "女仙帽子灵性向七阶", Materials = {"7阶仙器卷轴女仙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女仙帽子力量向六阶'] = {Target = "女仙帽子力量向七阶", Materials = {"7阶仙器卷轴女仙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女仙帽子敏捷向六阶'] = {Target = "女仙帽子敏捷向七阶", Materials = {"7阶仙器卷轴女仙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男龙帽子根骨向六阶'] = {Target = "男龙帽子根骨向七阶", Materials = {"7阶仙器卷轴男龙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男龙帽子力量向六阶'] = {Target = "男龙帽子力量向七阶", Materials = {"7阶仙器卷轴男龙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男龙帽子敏捷向六阶'] = {Target = "男龙帽子敏捷向七阶", Materials = {"7阶仙器卷轴男龙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女龙帽子根骨向六阶'] = {Target = "女龙帽子根骨向七阶", Materials = {"7阶仙器卷轴女龙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女龙帽子力量向六阶'] = {Target = "女龙帽子力量向七阶", Materials = {"7阶仙器卷轴女龙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女龙帽子敏捷向六阶'] = {Target = "女龙帽子敏捷向七阶", Materials = {"7阶仙器卷轴女龙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	['男魔衣服根骨向'] = {Target = "男魔衣服根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男魔衣服力量向'] = {Target = "男魔衣服力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男魔衣服敏捷向'] = {Target = "男魔衣服敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女魔衣服根骨向'] = {Target = "女魔衣服根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女魔衣服力量向'] = {Target = "女魔衣服力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女魔衣服敏捷向'] = {Target = "女魔衣服敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男人衣服根骨向'] = {Target = "男人衣服根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男人衣服力量向'] = {Target = "男人衣服力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男人衣服敏捷向'] = {Target = "男人衣服敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女人衣服根骨向'] = {Target = "女人衣服根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女人衣服力量向'] = {Target = "女人衣服力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女人衣服敏捷向'] = {Target = "女人衣服敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男鬼衣服根骨向'] = {Target = "男鬼衣服根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男鬼衣服力量向'] = {Target = "男鬼衣服力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男鬼衣服敏捷向'] = {Target = "男鬼衣服敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女鬼衣服根骨向'] = {Target = "女鬼衣服根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女鬼衣服力量向'] = {Target = "女鬼衣服力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女鬼衣服敏捷向'] = {Target = "女鬼衣服敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男仙衣服灵性向'] = {Target = "男仙衣服灵性向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男仙衣服力量向'] = {Target = "男仙衣服力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男仙衣服敏捷向'] = {Target = "男仙衣服敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女仙衣服灵性向'] = {Target = "女仙衣服灵性向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女仙衣服力量向'] = {Target = "女仙衣服力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女仙衣服敏捷向'] = {Target = "女仙衣服敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男龙衣服根骨向'] = {Target = "男龙衣服根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男龙衣服力量向'] = {Target = "男龙衣服力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男龙衣服敏捷向'] = {Target = "男龙衣服敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女龙衣服根骨向'] = {Target = "女龙衣服根骨向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女龙衣服力量向'] = {Target = "女龙衣服力量向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['女龙衣服敏捷向'] = {Target = "女龙衣服敏捷向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['男魔衣服根骨向二阶'] = {Target = "男魔衣服根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男魔衣服力量向二阶'] = {Target = "男魔衣服力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男魔衣服敏捷向二阶'] = {Target = "男魔衣服敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女魔衣服根骨向二阶'] = {Target = "女魔衣服根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女魔衣服力量向二阶'] = {Target = "女魔衣服力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女魔衣服敏捷向二阶'] = {Target = "女魔衣服敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男人衣服根骨向二阶'] = {Target = "男人衣服根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男人衣服力量向二阶'] = {Target = "男人衣服力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男人衣服敏捷向二阶'] = {Target = "男人衣服敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女人衣服根骨向二阶'] = {Target = "女人衣服根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女人衣服力量向二阶'] = {Target = "女人衣服力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女人衣服敏捷向二阶'] = {Target = "女人衣服敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男鬼衣服根骨向二阶'] = {Target = "男鬼衣服根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男鬼衣服力量向二阶'] = {Target = "男鬼衣服力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男鬼衣服敏捷向二阶'] = {Target = "男鬼衣服敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女鬼衣服根骨向二阶'] = {Target = "女鬼衣服根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女鬼衣服力量向二阶'] = {Target = "女鬼衣服力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女鬼衣服敏捷向二阶'] = {Target = "女鬼衣服敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男仙衣服灵性向二阶'] = {Target = "男仙衣服灵性向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男仙衣服力量向二阶'] = {Target = "男仙衣服力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男仙衣服敏捷向二阶'] = {Target = "男仙衣服敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女仙衣服灵性向二阶'] = {Target = "女仙衣服灵性向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女仙衣服力量向二阶'] = {Target = "女仙衣服力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女仙衣服敏捷向二阶'] = {Target = "女仙衣服敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男龙衣服根骨向二阶'] = {Target = "男龙衣服根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男龙衣服力量向二阶'] = {Target = "男龙衣服力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男龙衣服敏捷向二阶'] = {Target = "男龙衣服敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女龙衣服根骨向二阶'] = {Target = "女龙衣服根骨向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女龙衣服力量向二阶'] = {Target = "女龙衣服力量向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['女龙衣服敏捷向二阶'] = {Target = "女龙衣服敏捷向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType =1},
	['男魔衣服根骨向三阶'] = {Target = "男魔衣服根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男魔衣服力量向三阶'] = {Target = "男魔衣服力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男魔衣服敏捷向三阶'] = {Target = "男魔衣服敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女魔衣服根骨向三阶'] = {Target = "女魔衣服根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女魔衣服力量向三阶'] = {Target = "女魔衣服力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女魔衣服敏捷向三阶'] = {Target = "女魔衣服敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男人衣服根骨向三阶'] = {Target = "男人衣服根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男人衣服力量向三阶'] = {Target = "男人衣服力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男人衣服敏捷向三阶'] = {Target = "男人衣服敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女人衣服根骨向三阶'] = {Target = "女人衣服根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女人衣服力量向三阶'] = {Target = "女人衣服力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女人衣服敏捷向三阶'] = {Target = "女人衣服敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男鬼衣服根骨向三阶'] = {Target = "男鬼衣服根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男鬼衣服力量向三阶'] = {Target = "男鬼衣服力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男鬼衣服敏捷向三阶'] = {Target = "男鬼衣服敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女鬼衣服根骨向三阶'] = {Target = "女鬼衣服根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女鬼衣服力量向三阶'] = {Target = "女鬼衣服力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女鬼衣服敏捷向三阶'] = {Target = "女鬼衣服敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男仙衣服灵性向三阶'] = {Target = "男仙衣服灵性向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男仙衣服力量向三阶'] = {Target = "男仙衣服力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男仙衣服敏捷向三阶'] = {Target = "男仙衣服敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女仙衣服灵性向三阶'] = {Target = "女仙衣服灵性向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女仙衣服力量向三阶'] = {Target = "女仙衣服力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女仙衣服敏捷向三阶'] = {Target = "女仙衣服敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男龙衣服根骨向三阶'] = {Target = "男龙衣服根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男龙衣服力量向三阶'] = {Target = "男龙衣服力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男龙衣服敏捷向三阶'] = {Target = "男龙衣服敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女龙衣服根骨向三阶'] = {Target = "女龙衣服根骨向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女龙衣服力量向三阶'] = {Target = "女龙衣服力量向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['女龙衣服敏捷向三阶'] = {Target = "女龙衣服敏捷向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['男魔衣服根骨向四阶'] = {Target = "男魔衣服根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男魔衣服力量向四阶'] = {Target = "男魔衣服力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男魔衣服敏捷向四阶'] = {Target = "男魔衣服敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女魔衣服根骨向四阶'] = {Target = "女魔衣服根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女魔衣服力量向四阶'] = {Target = "女魔衣服力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女魔衣服敏捷向四阶'] = {Target = "女魔衣服敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男人衣服根骨向四阶'] = {Target = "男人衣服根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男人衣服力量向四阶'] = {Target = "男人衣服力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男人衣服敏捷向四阶'] = {Target = "男人衣服敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女人衣服根骨向四阶'] = {Target = "女人衣服根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女人衣服力量向四阶'] = {Target = "女人衣服力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女人衣服敏捷向四阶'] = {Target = "女人衣服敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男鬼衣服根骨向四阶'] = {Target = "男鬼衣服根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男鬼衣服力量向四阶'] = {Target = "男鬼衣服力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男鬼衣服敏捷向四阶'] = {Target = "男鬼衣服敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女鬼衣服根骨向四阶'] = {Target = "女鬼衣服根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女鬼衣服力量向四阶'] = {Target = "女鬼衣服力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女鬼衣服敏捷向四阶'] = {Target = "女鬼衣服敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男仙衣服灵性向四阶'] = {Target = "男仙衣服灵性向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男仙衣服力量向四阶'] = {Target = "男仙衣服力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男仙衣服敏捷向四阶'] = {Target = "男仙衣服敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女仙衣服灵性向四阶'] = {Target = "女仙衣服灵性向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女仙衣服力量向四阶'] = {Target = "女仙衣服力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女仙衣服敏捷向四阶'] = {Target = "女仙衣服敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男龙衣服根骨向四阶'] = {Target = "男龙衣服根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男龙衣服力量向四阶'] = {Target = "男龙衣服力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['男龙衣服敏捷向四阶'] = {Target = "男龙衣服敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女龙衣服根骨向四阶'] = {Target = "女龙衣服根骨向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女龙衣服力量向四阶'] = {Target = "女龙衣服力量向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['女龙衣服敏捷向四阶'] = {Target = "女龙衣服敏捷向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	--['男魔衣服根骨向五阶'] = {Target = "男魔衣服根骨向六阶", Materials = {"6阶仙器卷轴男魔", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男魔衣服力量向五阶'] = {Target = "男魔衣服力量向六阶", Materials = {"6阶仙器卷轴男魔", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男魔衣服敏捷向五阶'] = {Target = "男魔衣服敏捷向六阶", Materials = {"6阶仙器卷轴男魔", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女魔衣服根骨向五阶'] = {Target = "女魔衣服根骨向六阶", Materials = {"6阶仙器卷轴女魔", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女魔衣服力量向五阶'] = {Target = "女魔衣服力量向六阶", Materials = {"6阶仙器卷轴女魔", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女魔衣服敏捷向五阶'] = {Target = "女魔衣服敏捷向六阶", Materials = {"6阶仙器卷轴女魔", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男人衣服根骨向五阶'] = {Target = "男人衣服根骨向六阶", Materials = {"6阶仙器卷轴男人", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男人衣服力量向五阶'] = {Target = "男人衣服力量向六阶", Materials = {"6阶仙器卷轴男人", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男人衣服敏捷向五阶'] = {Target = "男人衣服敏捷向六阶", Materials = {"6阶仙器卷轴男人", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女人衣服根骨向五阶'] = {Target = "女人衣服根骨向六阶", Materials = {"6阶仙器卷轴女人", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女人衣服力量向五阶'] = {Target = "女人衣服力量向六阶", Materials = {"6阶仙器卷轴女人", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女人衣服敏捷向五阶'] = {Target = "女人衣服敏捷向六阶", Materials = {"6阶仙器卷轴女人", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男鬼衣服根骨向五阶'] = {Target = "男鬼衣服根骨向六阶", Materials = {"6阶仙器卷轴男鬼", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男鬼衣服力量向五阶'] = {Target = "男鬼衣服力量向六阶", Materials = {"6阶仙器卷轴男鬼", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男鬼衣服敏捷向五阶'] = {Target = "男鬼衣服敏捷向六阶", Materials = {"6阶仙器卷轴男鬼", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女鬼衣服根骨向五阶'] = {Target = "女鬼衣服根骨向六阶", Materials = {"6阶仙器卷轴女鬼", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女鬼衣服力量向五阶'] = {Target = "女鬼衣服力量向六阶", Materials = {"6阶仙器卷轴女鬼", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女鬼衣服敏捷向五阶'] = {Target = "女鬼衣服敏捷向六阶", Materials = {"6阶仙器卷轴女鬼", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男仙衣服灵性向五阶'] = {Target = "男仙衣服灵性向六阶", Materials = {"6阶仙器卷轴男仙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男仙衣服力量向五阶'] = {Target = "男仙衣服力量向六阶", Materials = {"6阶仙器卷轴男仙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男仙衣服敏捷向五阶'] = {Target = "男仙衣服敏捷向六阶", Materials = {"6阶仙器卷轴男仙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女仙衣服灵性向五阶'] = {Target = "女仙衣服灵性向六阶", Materials = {"6阶仙器卷轴女仙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女仙衣服力量向五阶'] = {Target = "女仙衣服力量向六阶", Materials = {"6阶仙器卷轴女仙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女仙衣服敏捷向五阶'] = {Target = "女仙衣服敏捷向六阶", Materials = {"6阶仙器卷轴女仙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男龙衣服根骨向五阶'] = {Target = "男龙衣服根骨向六阶", Materials = {"6阶仙器卷轴男龙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男龙衣服力量向五阶'] = {Target = "男龙衣服力量向六阶", Materials = {"6阶仙器卷轴男龙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男龙衣服敏捷向五阶'] = {Target = "男龙衣服敏捷向六阶", Materials = {"6阶仙器卷轴男龙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女龙衣服根骨向五阶'] = {Target = "女龙衣服根骨向六阶", Materials = {"6阶仙器卷轴女龙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女龙衣服力量向五阶'] = {Target = "女龙衣服力量向六阶", Materials = {"6阶仙器卷轴女龙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['女龙衣服敏捷向五阶'] = {Target = "女龙衣服敏捷向六阶", Materials = {"6阶仙器卷轴女龙", "仙器碎片",90,"仙玉",30}, MoneyVal = 30000000, MoneyType = 1},
	--['男魔衣服根骨向六阶'] = {Target = "男魔衣服根骨向七阶", Materials = {"7阶仙器卷轴男魔", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男魔衣服力量向六阶'] = {Target = "男魔衣服力量向七阶", Materials = {"7阶仙器卷轴男魔", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男魔衣服敏捷向六阶'] = {Target = "男魔衣服敏捷向七阶", Materials = {"7阶仙器卷轴男魔", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女魔衣服根骨向六阶'] = {Target = "女魔衣服根骨向七阶", Materials = {"7阶仙器卷轴女魔", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女魔衣服力量向六阶'] = {Target = "女魔衣服力量向七阶", Materials = {"7阶仙器卷轴女魔", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女魔衣服敏捷向六阶'] = {Target = "女魔衣服敏捷向七阶", Materials = {"7阶仙器卷轴女魔", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男人衣服根骨向六阶'] = {Target = "男人衣服根骨向七阶", Materials = {"7阶仙器卷轴男人", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男人衣服力量向六阶'] = {Target = "男人衣服力量向七阶", Materials = {"7阶仙器卷轴男人", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男人衣服敏捷向六阶'] = {Target = "男人衣服敏捷向七阶", Materials = {"7阶仙器卷轴男人", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女人衣服根骨向六阶'] = {Target = "女人衣服根骨向七阶", Materials = {"7阶仙器卷轴女人", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女人衣服力量向六阶'] = {Target = "女人衣服力量向七阶", Materials = {"7阶仙器卷轴女人", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女人衣服敏捷向六阶'] = {Target = "女人衣服敏捷向七阶", Materials = {"7阶仙器卷轴女人", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男鬼衣服根骨向六阶'] = {Target = "男鬼衣服根骨向七阶", Materials = {"7阶仙器卷轴男鬼", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男鬼衣服力量向六阶'] = {Target = "男鬼衣服力量向七阶", Materials = {"7阶仙器卷轴男鬼", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男鬼衣服敏捷向六阶'] = {Target = "男鬼衣服敏捷向七阶", Materials = {"7阶仙器卷轴男鬼", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女鬼衣服根骨向六阶'] = {Target = "女鬼衣服根骨向七阶", Materials = {"7阶仙器卷轴女鬼", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女鬼衣服力量向六阶'] = {Target = "女鬼衣服力量向七阶", Materials = {"7阶仙器卷轴女鬼", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女鬼衣服敏捷向六阶'] = {Target = "女鬼衣服敏捷向七阶", Materials = {"7阶仙器卷轴女鬼", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男仙衣服灵性向六阶'] = {Target = "男仙衣服灵性向七阶", Materials = {"7阶仙器卷轴男仙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男仙衣服力量向六阶'] = {Target = "男仙衣服力量向七阶", Materials = {"7阶仙器卷轴男仙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男仙衣服敏捷向六阶'] = {Target = "男仙衣服敏捷向七阶", Materials = {"7阶仙器卷轴男仙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女仙衣服灵性向六阶'] = {Target = "女仙衣服灵性向七阶", Materials = {"7阶仙器卷轴女仙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女仙衣服力量向六阶'] = {Target = "女仙衣服力量向七阶", Materials = {"7阶仙器卷轴女仙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女仙衣服敏捷向六阶'] = {Target = "女仙衣服敏捷向七阶", Materials = {"7阶仙器卷轴女仙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男龙衣服根骨向六阶'] = {Target = "男龙衣服根骨向七阶", Materials = {"7阶仙器卷轴男龙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男龙衣服力量向六阶'] = {Target = "男龙衣服力量向七阶", Materials = {"7阶仙器卷轴男龙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['男龙衣服敏捷向六阶'] = {Target = "男龙衣服敏捷向七阶", Materials = {"7阶仙器卷轴男龙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女龙衣服根骨向六阶'] = {Target = "女龙衣服根骨向七阶", Materials = {"7阶仙器卷轴女龙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女龙衣服力量向六阶'] = {Target = "女龙衣服力量向七阶", Materials = {"7阶仙器卷轴女龙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	--['女龙衣服敏捷向六阶'] = {Target = "女龙衣服敏捷向七阶", Materials = {"7阶仙器卷轴女龙", "仙器碎片",100,"仙玉",40}, MoneyVal = 36000000, MoneyType = 1},
	['通用腰带倍道向'] = {Target = "通用腰带倍道向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['通用腰带负速向'] = {Target = "通用腰带负速向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['通用腰带倍道向二阶'] = {Target = "通用腰带倍道向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType = 1},
	['通用腰带负速向二阶'] = {Target = "通用腰带负速向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType = 1},
	['通用腰带倍道向三阶'] = {Target = "通用腰带倍道向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['通用腰带负速向三阶'] = {Target = "通用腰带负速向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['通用腰带倍道向四阶'] = {Target = "通用腰带倍道向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['通用腰带负速向四阶'] = {Target = "通用腰带负速向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	--['通用腰带倍道向五阶'] = {Target = "通用腰带倍道向六阶", Materials = {"仙器碎片",250}, MoneyVal = 7000, MoneyType = 1},
	--['通用腰带负速向五阶'] = {Target = "通用腰带负速向六阶", Materials = {"仙器碎片",250}, MoneyVal = 7000, MoneyType = 1},
	--['通用腰带倍道向六阶'] = {Target = "通用腰带倍道向七阶", Materials = {"仙器碎片",300}, MoneyVal = 8000, MoneyType = 1},
	--['通用腰带负速向六阶'] = {Target = "通用腰带负速向七阶", Materials = {"仙器碎片",300}, MoneyVal = 8000, MoneyType = 1},
	['通用挂坠气血向'] = {Target = "通用挂坠气血向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['通用挂坠倍道向'] = {Target = "通用挂坠倍道向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['通用挂坠物理向'] = {Target = "通用挂坠物理向二阶", Materials = {"仙器碎片",50}, MoneyVal = 1000, MoneyType = 1},
	['通用挂坠气血向二阶'] = {Target = "通用挂坠气血向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType = 1},
	['通用挂坠倍道向二阶'] = {Target = "通用挂坠倍道向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType = 1},
	['通用挂坠物理向二阶'] = {Target = "通用挂坠物理向三阶", Materials = {"仙器碎片",100}, MoneyVal = 2000, MoneyType = 1},
	['通用挂坠气血向三阶'] = {Target = "通用挂坠气血向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['通用挂坠倍道向三阶'] = {Target = "通用挂坠倍道向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['通用挂坠物理向三阶'] = {Target = "通用挂坠物理向四阶", Materials = {"仙器碎片",150}, MoneyVal = 4000, MoneyType = 1},
	['通用挂坠气血向四阶'] = {Target = "通用挂坠气血向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['通用挂坠倍道向四阶'] = {Target = "通用挂坠倍道向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	['通用挂坠物理向四阶'] = {Target = "通用挂坠物理向五阶", Materials = {"仙器碎片",200}, MoneyVal = 5000, MoneyType = 1},
	--['通用挂坠气血向五阶'] = {Target = "通用挂坠气血向六阶", Materials = {"仙器碎片",250}, MoneyVal = 7000, MoneyType = 1},
	--['通用挂坠倍道向五阶'] = {Target = "通用挂坠倍道向六阶", Materials = {"仙器碎片",250}, MoneyVal = 7000, MoneyType = 1},
	--['通用挂坠物理向五阶'] = {Target = "通用挂坠物理向六阶", Materials = {"仙器碎片",250}, MoneyVal = 7000, MoneyType = 1},
	--['通用挂坠气血向六阶'] = {Target = "通用挂坠气血向七阶", Materials = {"仙器碎片",300}, MoneyVal = 8000, MoneyType = 1},
	--['通用挂坠倍道向六阶'] = {Target = "通用挂坠倍道向七阶", Materials = {"仙器碎片",300}, MoneyVal = 8000, MoneyType = 1},
	--['通用挂坠物理向六阶'] = {Target = "通用挂坠物理向七阶", Materials = {"仙器碎片",300}, MoneyVal = 8000, MoneyType = 1},
	['通用护腕灵性向'] = {Target = "通用护腕灵性向二阶", Materials = {"玄铁",30}, MoneyVal = 200000, MoneyType = 5},
	['通用护腕根骨向'] = {Target = "通用护腕根骨向二阶", Materials = {"玄铁",30}, MoneyVal = 200000, MoneyType = 5},
	['通用护腕力量向'] = {Target = "通用护腕力量向二阶", Materials = {"玄铁",30}, MoneyVal = 200000, MoneyType = 5},
	['通用护腕敏捷向'] = {Target = "通用护腕敏捷向二阶", Materials = {"玄铁",30}, MoneyVal = 200000, MoneyType = 5},
	['通用护腕灵性向二阶'] = {Target = "通用护腕灵性向三阶", Materials = {"玄铁",60}, MoneyVal = 400000, MoneyType = 5},
	['通用护腕根骨向二阶'] = {Target = "通用护腕根骨向三阶", Materials = {"玄铁",60}, MoneyVal = 400000, MoneyType = 5},
	['通用护腕力量向二阶'] = {Target = "通用护腕力量向三阶", Materials = {"玄铁",60}, MoneyVal = 400000, MoneyType = 5},
	['通用护腕敏捷向二阶'] = {Target = "通用护腕敏捷向三阶", Materials = {"玄铁",60}, MoneyVal = 400000, MoneyType = 5},
	['通用护腕灵性向三阶'] = {Target = "通用护腕灵性向四阶", Materials = {"玄铁",90}, MoneyVal = 800000, MoneyType = 5},
	['通用护腕根骨向三阶'] = {Target = "通用护腕根骨向四阶", Materials = {"玄铁",90}, MoneyVal = 800000, MoneyType = 5},
	['通用护腕力量向三阶'] = {Target = "通用护腕力量向四阶", Materials = {"玄铁",90}, MoneyVal = 800000, MoneyType = 5},
	['通用护腕敏捷向三阶'] = {Target = "通用护腕敏捷向四阶", Materials = {"玄铁",90}, MoneyVal = 800000, MoneyType = 5},
	['通用护腕灵性向四阶'] = {Target = "通用护腕灵性向五阶", Materials = {"玄铁",120}, MoneyVal = 1600000, MoneyType = 5},
	['通用护腕根骨向四阶'] = {Target = "通用护腕根骨向五阶", Materials = {"玄铁",120}, MoneyVal = 1600000, MoneyType = 5},
	['通用护腕力量向四阶'] = {Target = "通用护腕力量向五阶", Materials = {"玄铁",120}, MoneyVal = 1600000, MoneyType = 5},
	['通用护腕敏捷向四阶'] = {Target = "通用护腕敏捷向五阶", Materials = {"玄铁",120}, MoneyVal = 1600000, MoneyType = 5},
	--['通用护腕灵性向五阶'] = {Target = "通用护腕灵性向六阶", Materials = {"玄铁",150}, MoneyVal = 30000000, MoneyType = 5},
	--['通用护腕根骨向五阶'] = {Target = "通用护腕根骨向六阶", Materials = {"玄铁",150}, MoneyVal = 30000000, MoneyType = 5},
	--['通用护腕力量向五阶'] = {Target = "通用护腕力量向六阶", Materials = {"玄铁",150}, MoneyVal = 30000000, MoneyType = 5},
	--['通用护腕敏捷向五阶'] = {Target = "通用护腕敏捷向六阶", Materials = {"玄铁",150}, MoneyVal = 30000000, MoneyType = 5},
	--['通用护腕灵性向六阶'] = {Target = "通用护腕灵性向七阶", Materials = {"玄铁",180}, MoneyVal = 36000000, MoneyType = 5},
	--['通用护腕根骨向六阶'] = {Target = "通用护腕根骨向七阶", Materials = {"玄铁",180}, MoneyVal = 36000000, MoneyType = 5},
	--['通用护腕力量向六阶'] = {Target = "通用护腕力量向七阶", Materials = {"玄铁",180}, MoneyVal = 36000000, MoneyType = 5},
	--['通用护腕敏捷向六阶'] = {Target = "通用护腕敏捷向七阶", Materials = {"玄铁",180}, MoneyVal = 36000000, MoneyType = 5},
	['通用戒指灵性向'] = {Target = "通用戒指灵性向二阶", Materials = {"玄铁",30}, MoneyVal = 200000, MoneyType = 5},
	['通用戒指根骨向'] = {Target = "通用戒指根骨向二阶", Materials = {"玄铁",30}, MoneyVal = 200000, MoneyType = 5},
	['通用戒指力量向'] = {Target = "通用戒指力量向二阶", Materials = {"玄铁",30}, MoneyVal = 200000, MoneyType = 5},
	['通用戒指敏捷向'] = {Target = "通用戒指敏捷向二阶", Materials = {"玄铁",30}, MoneyVal = 200000, MoneyType = 5},
	['通用戒指灵性向二阶'] = {Target = "通用戒指灵性向三阶", Materials = {"玄铁",60}, MoneyVal = 400000, MoneyType = 5},
	['通用戒指根骨向二阶'] = {Target = "通用戒指根骨向三阶", Materials = {"玄铁",60}, MoneyVal = 400000, MoneyType = 5},
	['通用戒指力量向二阶'] = {Target = "通用戒指力量向三阶", Materials = {"玄铁",60}, MoneyVal = 400000, MoneyType = 5},
	['通用戒指敏捷向二阶'] = {Target = "通用戒指敏捷向三阶", Materials = {"玄铁",60}, MoneyVal = 400000, MoneyType = 5},
	['通用戒指灵性向三阶'] = {Target = "通用戒指灵性向四阶", Materials = {"玄铁",90}, MoneyVal = 800000, MoneyType = 5},
	['通用戒指根骨向三阶'] = {Target = "通用戒指根骨向四阶", Materials = {"玄铁",90}, MoneyVal = 800000, MoneyType = 5},
	['通用戒指力量向三阶'] = {Target = "通用戒指力量向四阶", Materials = {"玄铁",90}, MoneyVal = 800000, MoneyType = 5},
	['通用戒指敏捷向三阶'] = {Target = "通用戒指敏捷向四阶", Materials = {"玄铁",90}, MoneyVal = 800000, MoneyType = 5},
	['通用戒指灵性向四阶'] = {Target = "通用戒指灵性向五阶", Materials = {"玄铁",120}, MoneyVal = 1600000, MoneyType = 5},
	['通用戒指根骨向四阶'] = {Target = "通用戒指根骨向五阶", Materials = {"玄铁",120}, MoneyVal = 1600000, MoneyType = 5},
	['通用戒指力量向四阶'] = {Target = "通用戒指力量向五阶", Materials = {"玄铁",120}, MoneyVal = 1600000, MoneyType = 5},
	['通用戒指敏捷向四阶'] = {Target = "通用戒指敏捷向五阶", Materials = {"玄铁",120}, MoneyVal = 1600000, MoneyType = 5},
	--['通用戒指灵性向五阶'] = {Target = "通用戒指灵性向六阶", Materials = {"玄铁",150}, MoneyVal = 30000000, MoneyType = 5},
	--['通用戒指根骨向五阶'] = {Target = "通用戒指根骨向六阶", Materials = {"玄铁",150}, MoneyVal = 30000000, MoneyType = 5},
	--['通用戒指力量向五阶'] = {Target = "通用戒指力量向六阶", Materials = {"玄铁",150}, MoneyVal = 30000000, MoneyType = 5},
	--['通用戒指敏捷向五阶'] = {Target = "通用戒指敏捷向六阶", Materials = {"玄铁",150}, MoneyVal = 30000000, MoneyType = 5},
	--['通用戒指灵性向六阶'] = {Target = "通用戒指灵性向七阶", Materials = {"玄铁",180}, MoneyVal = 36000000, MoneyType = 5},
	--['通用戒指根骨向六阶'] = {Target = "通用戒指根骨向七阶", Materials = {"玄铁",180}, MoneyVal = 36000000, MoneyType = 5},
	--['通用戒指力量向六阶'] = {Target = "通用戒指力量向七阶", Materials = {"玄铁",180}, MoneyVal = 36000000, MoneyType = 5},
	--['通用戒指敏捷向六阶'] = {Target = "通用戒指敏捷向七阶", Materials = {"玄铁",180}, MoneyVal = 36000000, MoneyType = 5},
	['通用项链灵性向'] = {Target = "通用项链灵性向二阶", Materials = {"玄铁",30}, MoneyVal = 200000, MoneyType = 5},
	['通用项链根骨向'] = {Target = "通用项链根骨向二阶", Materials = {"玄铁",30}, MoneyVal = 200000, MoneyType = 5},
	['通用项链力量向'] = {Target = "通用项链力量向二阶", Materials = {"玄铁",30}, MoneyVal = 200000, MoneyType = 5},
	['通用项链敏捷向'] = {Target = "通用项链敏捷向二阶", Materials = {"玄铁",30}, MoneyVal = 200000, MoneyType = 5},
	['通用项链灵性向二阶'] = {Target = "通用项链灵性向三阶", Materials = {"玄铁",60}, MoneyVal = 400000, MoneyType = 5},
	['通用项链根骨向二阶'] = {Target = "通用项链根骨向三阶", Materials = {"玄铁",60}, MoneyVal = 400000, MoneyType = 5},
	['通用项链力量向二阶'] = {Target = "通用项链力量向三阶", Materials = {"玄铁",60}, MoneyVal = 400000, MoneyType = 5},
	['通用项链敏捷向二阶'] = {Target = "通用项链敏捷向三阶", Materials = {"玄铁",60}, MoneyVal = 400000, MoneyType = 5},
	['通用项链灵性向三阶'] = {Target = "通用项链灵性向四阶", Materials = {"玄铁",90}, MoneyVal = 800000, MoneyType = 5},
	['通用项链根骨向三阶'] = {Target = "通用项链根骨向四阶", Materials = {"玄铁",90}, MoneyVal = 800000, MoneyType = 5},
	['通用项链力量向三阶'] = {Target = "通用项链力量向四阶", Materials = {"玄铁",90}, MoneyVal = 800000, MoneyType = 5},
	['通用项链敏捷向三阶'] = {Target = "通用项链敏捷向四阶", Materials = {"玄铁",90}, MoneyVal = 800000, MoneyType = 5},
	['通用项链灵性向四阶'] = {Target = "通用项链灵性向五阶", Materials = {"玄铁",120}, MoneyVal = 1600000, MoneyType = 5},
	['通用项链根骨向四阶'] = {Target = "通用项链根骨向五阶", Materials = {"玄铁",120}, MoneyVal = 1600000, MoneyType = 5},
	['通用项链力量向四阶'] = {Target = "通用项链力量向五阶", Materials = {"玄铁",120}, MoneyVal = 1600000, MoneyType = 5},
	['通用项链敏捷向四阶'] = {Target = "通用项链敏捷向五阶", Materials = {"玄铁",120}, MoneyVal = 1600000, MoneyType = 5},
	--['通用项链灵性向五阶'] = {Target = "通用项链灵性向六阶", Materials = {"玄铁",150}, MoneyVal = 30000000, MoneyType = 5},
	--['通用项链根骨向五阶'] = {Target = "通用项链根骨向六阶", Materials = {"玄铁",150}, MoneyVal = 30000000, MoneyType = 5},
	--['通用项链力量向五阶'] = {Target = "通用项链力量向六阶", Materials = {"玄铁",150}, MoneyVal = 30000000, MoneyType = 5},
	--['通用项链敏捷向五阶'] = {Target = "通用项链敏捷向六阶", Materials = {"玄铁",150}, MoneyVal = 30000000, MoneyType = 5},
	--['通用项链灵性向六阶'] = {Target = "通用项链灵性向七阶", Materials = {"玄铁",180}, MoneyVal = 36000000, MoneyType = 5},
	--['通用项链根骨向六阶'] = {Target = "通用项链根骨向七阶", Materials = {"玄铁",180}, MoneyVal = 36000000, MoneyType = 5},
	--['通用项链力量向六阶'] = {Target = "通用项链力量向七阶", Materials = {"玄铁",180}, MoneyVal = 36000000, MoneyType = 5},
	--['通用项链敏捷向六阶'] = {Target = "通用项链敏捷向七阶", Materials = {"玄铁",180}, MoneyVal = 36000000, MoneyType = 5},
	['通用靴子灵性向'] = {Target = "通用靴子灵性向二阶", Materials = {"玄铁",30}, MoneyVal = 200000, MoneyType = 5},
	['通用靴子根骨向'] = {Target = "通用靴子根骨向二阶", Materials = {"玄铁",30}, MoneyVal = 200000, MoneyType = 5},
	['通用靴子力量向'] = {Target = "通用靴子力量向二阶", Materials = {"玄铁",30}, MoneyVal = 200000, MoneyType = 5},
	['通用靴子敏捷向'] = {Target = "通用靴子敏捷向二阶", Materials = {"玄铁",30}, MoneyVal = 200000, MoneyType = 5},
	['通用靴子灵性向二阶'] = {Target = "通用靴子灵性向三阶", Materials = {"玄铁",60}, MoneyVal = 400000, MoneyType = 5},
	['通用靴子根骨向二阶'] = {Target = "通用靴子根骨向三阶", Materials = {"玄铁",60}, MoneyVal = 400000, MoneyType = 5},
	['通用靴子力量向二阶'] = {Target = "通用靴子力量向三阶", Materials = {"玄铁",60}, MoneyVal = 400000, MoneyType = 5},
	['通用靴子敏捷向二阶'] = {Target = "通用靴子敏捷向三阶", Materials = {"玄铁",60}, MoneyVal = 400000, MoneyType = 5},
	['通用靴子灵性向三阶'] = {Target = "通用靴子灵性向四阶", Materials = {"玄铁",90}, MoneyVal = 800000, MoneyType = 5},
	['通用靴子根骨向三阶'] = {Target = "通用靴子根骨向四阶", Materials = {"玄铁",90}, MoneyVal = 800000, MoneyType = 5},
	['通用靴子力量向三阶'] = {Target = "通用靴子力量向四阶", Materials = {"玄铁",90}, MoneyVal = 800000, MoneyType = 5},
	['通用靴子敏捷向三阶'] = {Target = "通用靴子敏捷向四阶", Materials = {"玄铁",90}, MoneyVal = 800000, MoneyType = 5},
	['通用靴子灵性向四阶'] = {Target = "通用靴子灵性向五阶", Materials = {"玄铁",120}, MoneyVal = 1600000, MoneyType = 5},
	['通用靴子根骨向四阶'] = {Target = "通用靴子根骨向五阶", Materials = {"玄铁",120}, MoneyVal = 1600000, MoneyType = 5},
	['通用靴子力量向四阶'] = {Target = "通用靴子力量向五阶", Materials = {"玄铁",120}, MoneyVal = 1600000, MoneyType = 5},
	['通用靴子敏捷向四阶'] = {Target = "通用靴子敏捷向五阶", Materials = {"玄铁",120}, MoneyVal = 1600000, MoneyType = 5},
	--['通用靴子灵性向五阶'] = {Target = "通用靴子灵性向六阶", Materials = {"玄铁",150}, MoneyVal = 30000000, MoneyType = 5},
	--['通用靴子根骨向五阶'] = {Target = "通用靴子根骨向六阶", Materials = {"玄铁",150}, MoneyVal = 30000000, MoneyType = 5},
	--['通用靴子力量向五阶'] = {Target = "通用靴子力量向六阶", Materials = {"玄铁",150}, MoneyVal = 30000000, MoneyType = 5},
	--['通用靴子敏捷向五阶'] = {Target = "通用靴子敏捷向六阶", Materials = {"玄铁",150}, MoneyVal = 30000000, MoneyType = 5},
	--['通用靴子灵性向六阶'] = {Target = "通用靴子灵性向七阶", Materials = {"玄铁",180}, MoneyVal = 36000000, MoneyType = 5},
	--['通用靴子根骨向六阶'] = {Target = "通用靴子根骨向七阶", Materials = {"玄铁",180}, MoneyVal = 36000000, MoneyType = 5},
	--['通用靴子力量向六阶'] = {Target = "通用靴子力量向七阶", Materials = {"玄铁",180}, MoneyVal = 36000000, MoneyType = 5},
	--['通用靴子敏捷向六阶'] = {Target = "通用靴子敏捷向七阶", Materials = {"玄铁",180}, MoneyVal = 36000000, MoneyType = 5},
	['1级护身符'] = {Target = "2级护身符", Materials = {"帮战精华",20}, MoneyVal = 200000, MoneyType = 5},
	['2级护身符'] = {Target = "3级护身符", Materials = {"帮战精华",40}, MoneyVal = 400000, MoneyType = 5},
	['3级护身符'] = {Target = "4级护身符", Materials = {"帮战精华",60}, MoneyVal = 600000, MoneyType = 5},
	['4级护身符'] = {Target = "5级护身符", Materials = {"帮战精华",80}, MoneyVal = 800000, MoneyType = 5},
	['5级护身符'] = {Target = "6级护身符", Materials = {"帮战精华",100}, MoneyVal = 1600000, MoneyType = 5},
	['6级护身符'] = {Target = "7级护身符", Materials = {"帮战精华",150}, MoneyVal = 3200000, MoneyType = 5},
	['7级护身符'] = {Target = "8级护身符", Materials = {"帮战精华",200}, MoneyVal = 6400000, MoneyType = 5},
}


