RandomPetGiftsConfig = {}

RandomPetGiftsConfig.Main = {
--	['宠物礼包1'] = {{PetKey = "代理七仙女", Level = 1, Bind = 0, Rand = 500},},
	['支线瑞兽幼崽宝宝'] = {{PetKey = "支线瑞兽幼崽宝宝", Level = 1, Bind = 1, Rand = 500},},
	['支线灵木怪宝宝'] = {{PetKey = "支线灵木怪宝宝", Level = 1, Bind = 1, Rand = 500},},
	['支线赤炎狼宝宝'] = {{PetKey = "支线赤炎狼宝宝", Level = 1, Bind = 1, Rand = 500},},
	['支线洞花妖宝宝'] = {{PetKey = "支线洞花妖宝宝", Level = 1, Bind = 1, Rand = 500},},
	['支线素尾白狐宝宝'] = {{PetKey = "支线素尾白狐宝宝", Level = 1, Bind = 1, Rand = 500},},
	['支线踏火神犀宝宝'] = {{PetKey = "支线踏火神犀宝宝", Level = 1, Bind = 1, Rand = 500},},
	['神兽猪宠物'] = {{PetKey = "神兽猪", Level = 1, Bind = 1, Rand = 500},},
	['神兽礼包'] = {{PetKey = "神兽猪", Level = 1, Bind = 0, Rand = 500},},
	['艾小米宝宝'] = {{PetKey = "艾小米宝宝", Level = 1, Bind = 1, Rand = 500},},
	['幻灵鹿宝宝'] = {{PetKey = "幻灵鹿宝宝", Level = 1, Bind = 1, Rand = 500},},
	['小绵羊宝宝'] = {{PetKey = "小绵羊宝宝", Level = 1, Bind = 0, Rand = 500},},
	['蟹将军宝宝'] = {{PetKey = "蟹将军宝宝", Level = 1, Bind = 0, Rand = 500},},
	['野猪妖宝宝'] = {{PetKey = "野猪妖宝宝", Level = 1, Bind = 0, Rand = 500},},
	['无根草宝宝'] = {{PetKey = "无根草宝宝", Level = 1, Bind = 0, Rand = 500},},
	['行者游魂宝宝'] = {{PetKey = "行者游魂宝宝", Level = 1, Bind = 0, Rand = 500},},
	['浣灵熊宝宝'] = {{PetKey = "浣灵熊宝宝", Level = 1, Bind = 0, Rand = 500},},
	['小虎妖宝宝'] = {{PetKey = "小虎妖宝宝", Level = 1, Bind = 0, Rand = 500},},
	['旋龟宝宝'] = {{PetKey = "旋龟宝宝", Level = 1, Bind = 0, Rand = 500},},
	['岩穴鳄宝宝'] = {{PetKey = "岩穴鳄宝宝", Level = 1, Bind = 0, Rand = 500},},
	['山贼斥候宝宝'] = {{PetKey = "山贼斥候宝宝", Level = 1, Bind = 0, Rand = 500},},
	['瑞兽幼崽宝宝'] = {{PetKey = "瑞兽幼崽宝宝", Level = 1, Bind = 0, Rand = 500},},
	['雪坊主宝宝'] = {{PetKey = "雪坊主宝宝", Level = 1, Bind = 0, Rand = 500},},
	['女尸怨灵宝宝'] = {{PetKey = "女尸怨灵宝宝", Level = 1, Bind = 0, Rand = 500},},
	['水判官宝宝'] = {{PetKey = "水判官宝宝", Level = 1, Bind = 0, Rand = 500},},
	['青冥灯宝宝'] = {{PetKey = "青冥灯宝宝", Level = 1, Bind = 0, Rand = 500},},
	['灵木怪宝宝'] = {{PetKey = "灵木怪宝宝", Level = 1, Bind = 0, Rand = 500},},
	['幻灵鹿宝宝2'] = {{PetKey = "幻灵鹿宝宝", Level = 1, Bind = 0, Rand = 500},},
	['剧毒蜘蛛宝宝'] = {{PetKey = "剧毒蜘蛛宝宝", Level = 1, Bind = 0, Rand = 500},},
	['魅音狐宝宝'] = {{PetKey = "魅音狐宝宝", Level = 1, Bind = 0, Rand = 500},},
	['赤炎狼宝宝'] = {{PetKey = "赤炎狼宝宝", Level = 1, Bind = 0, Rand = 500},},
	['土灵熊宝宝'] = {{PetKey = "土灵熊宝宝", Level = 1, Bind = 0, Rand = 500},},
	['裂天兕宝宝'] = {{PetKey = "裂天兕宝宝", Level = 1, Bind = 0, Rand = 500},},
	['血量资质宝宝1'] = {{PetKey = "血量资质宝宝1", Level = 1, Bind = 1, Rand = 500},},	
	['物攻资质宝宝1'] = {{PetKey = "物攻资质宝宝1", Level = 1, Bind = 1, Rand = 500},},
	['物防资质宝宝1'] = {{PetKey = "物防资质宝宝1", Level = 1, Bind = 1, Rand = 500},},
	['法防资质宝宝1'] = {{PetKey = "法防资质宝宝1", Level = 1, Bind = 1, Rand = 500},},
	['法攻资质宝宝1'] = {{PetKey = "法攻资质宝宝1", Level = 1, Bind = 1, Rand = 500},},
	['速度资质宝宝1'] = {{PetKey = "速度资质宝宝1", Level = 1, Bind = 1, Rand = 500},},
	['悟性资质宝宝1'] = {{PetKey = "悟性资质宝宝1", Level = 1, Bind = 1, Rand = 500},},
	['血量资质宝宝2'] = {{PetKey = "血量资质宝宝2", Level = 1, Bind = 1, Rand = 500},},
	['物攻资质宝宝2'] = {{PetKey = "物攻资质宝宝2", Level = 1, Bind = 1, Rand = 500},},
	['物防资质宝宝2'] = {{PetKey = "物防资质宝宝2", Level = 1, Bind = 1, Rand = 500},},
	['法防资质宝宝2'] = {{PetKey = "法防资质宝宝2", Level = 1, Bind = 1, Rand = 500},},
	['法攻资质宝宝2'] = {{PetKey = "法攻资质宝宝2", Level = 1, Bind = 1, Rand = 500},},
	['速度资质宝宝2'] = {{PetKey = "速度资质宝宝2", Level = 1, Bind = 1, Rand = 500},},
	['悟性资质宝宝2'] = {{PetKey = "悟性资质宝宝2", Level = 1, Bind = 1, Rand = 500},},
	['血量资质宝宝3'] = {{PetKey = "血量资质宝宝3", Level = 1, Bind = 1, Rand = 500},},
	['物攻资质宝宝3'] = {{PetKey = "物攻资质宝宝3", Level = 1, Bind = 1, Rand = 500},},
	['物防资质宝宝3'] = {{PetKey = "物防资质宝宝3", Level = 1, Bind = 1, Rand = 500},},
	['法防资质宝宝3'] = {{PetKey = "法防资质宝宝3", Level = 1, Bind = 1, Rand = 500},},
	['法攻资质宝宝3'] = {{PetKey = "法攻资质宝宝3", Level = 1, Bind = 1, Rand = 500},},
	['速度资质宝宝3'] = {{PetKey = "速度资质宝宝3", Level = 1, Bind = 1, Rand = 500},},
	['悟性资质宝宝3'] = {{PetKey = "悟性资质宝宝3", Level = 1, Bind = 1, Rand = 500},},
	['普通吞噬宠物'] = {{PetKey = "普通吞噬宠物", Level = 1, Bind = 1, Rand = 500},},	
	['宝宝吞噬宠物'] = {{PetKey = "宝宝吞噬宠物", Level = 1, Bind = 1, Rand = 500},},
	['变异吞噬宠物'] = {{PetKey = "变异吞噬宠物", Level = 1, Bind = 1, Rand = 500},},
	['仙兽吞噬宠物'] = {{PetKey = "仙兽吞噬宠物", Level = 1, Bind = 1, Rand = 500},},
	['神兽吞噬宠物'] = {{PetKey = "神兽吞噬宠物", Level = 1, Bind = 1, Rand = 500},},
	['魔兽吞噬宠物'] = {{PetKey = "魔兽吞噬宠物", Level = 1, Bind = 1, Rand = 500},},
	['圣兽吞噬宠物'] = {{PetKey = "圣兽吞噬宠物", Level = 1, Bind = 1, Rand = 500},},
	['元灵吞噬宠物'] = {{PetKey = "元灵吞噬宠物", Level = 1, Bind = 1, Rand = 500},},
	['洪荒吞噬宠物'] = {{PetKey = "洪荒吞噬宠物", Level = 1, Bind = 1, Rand = 500},},
	['普通吞噬宠物1'] = {{PetKey = "普通吞噬宠物1", Level = 1, Bind = 1, Rand = 500},},	
	['宝宝吞噬宠物1'] = {{PetKey = "宝宝吞噬宠物1", Level = 1, Bind = 1, Rand = 500},},
	['变异吞噬宠物1'] = {{PetKey = "变异吞噬宠物1", Level = 1, Bind = 1, Rand = 500},},
	['仙兽吞噬宠物1'] = {{PetKey = "仙兽吞噬宠物1", Level = 1, Bind = 1, Rand = 500},},
	['神兽吞噬宠物1'] = {{PetKey = "神兽吞噬宠物1", Level = 1, Bind = 1, Rand = 500},},
	['魔兽吞噬宠物1'] = {{PetKey = "魔兽吞噬宠物1", Level = 1, Bind = 1, Rand = 500},},
	['圣兽吞噬宠物1'] = {{PetKey = "圣兽吞噬宠物1", Level = 1, Bind = 1, Rand = 500},},
	['元灵吞噬宠物1'] = {{PetKey = "元灵吞噬宠物1", Level = 1, Bind = 1, Rand = 500},},
	['洪荒吞噬宠物1'] = {{PetKey = "洪荒吞噬宠物1", Level = 1, Bind = 1, Rand = 500},},
	['普通吞噬宠物2'] = {{PetKey = "普通吞噬宠物2", Level = 1, Bind = 1, Rand = 500},},	
	['宝宝吞噬宠物2'] = {{PetKey = "宝宝吞噬宠物2", Level = 1, Bind = 1, Rand = 500},},
	['变异吞噬宠物2'] = {{PetKey = "变异吞噬宠物2", Level = 1, Bind = 1, Rand = 500},},
	['仙兽吞噬宠物2'] = {{PetKey = "仙兽吞噬宠物2", Level = 1, Bind = 1, Rand = 500},},
	['神兽吞噬宠物2'] = {{PetKey = "神兽吞噬宠物2", Level = 1, Bind = 1, Rand = 500},},
	['魔兽吞噬宠物2'] = {{PetKey = "魔兽吞噬宠物2", Level = 1, Bind = 1, Rand = 500},},
	['圣兽吞噬宠物2'] = {{PetKey = "圣兽吞噬宠物2", Level = 1, Bind = 1, Rand = 500},},
	['元灵吞噬宠物2'] = {{PetKey = "元灵吞噬宠物2", Level = 1, Bind = 1, Rand = 500},},
	['洪荒吞噬宠物2'] = {{PetKey = "洪荒吞噬宠物2", Level = 1, Bind = 1, Rand = 500},},
	['普通吞噬宠物3'] = {{PetKey = "普通吞噬宠物3", Level = 1, Bind = 1, Rand = 500},},	
	['宝宝吞噬宠物3'] = {{PetKey = "宝宝吞噬宠物3", Level = 1, Bind = 1, Rand = 500},},
	['变异吞噬宠物3'] = {{PetKey = "变异吞噬宠物3", Level = 1, Bind = 1, Rand = 500},},
	['仙兽吞噬宠物3'] = {{PetKey = "仙兽吞噬宠物3", Level = 1, Bind = 1, Rand = 500},},
	['神兽吞噬宠物3'] = {{PetKey = "神兽吞噬宠物3", Level = 1, Bind = 1, Rand = 500},},
	['魔兽吞噬宠物3'] = {{PetKey = "魔兽吞噬宠物3", Level = 1, Bind = 1, Rand = 500},},
	['圣兽吞噬宠物3'] = {{PetKey = "圣兽吞噬宠物3", Level = 1, Bind = 1, Rand = 500},},
	['元灵吞噬宠物3'] = {{PetKey = "元灵吞噬宠物3", Level = 1, Bind = 1, Rand = 500},},
	['洪荒吞噬宠物3'] = {{PetKey = "洪荒吞噬宠物3", Level = 1, Bind = 1, Rand = 500},},
	['普通吞噬宠物4'] = {{PetKey = "普通吞噬宠物4", Level = 1, Bind = 1, Rand = 500},},	
	['宝宝吞噬宠物4'] = {{PetKey = "宝宝吞噬宠物4", Level = 1, Bind = 1, Rand = 500},},
	['变异吞噬宠物4'] = {{PetKey = "变异吞噬宠物4", Level = 1, Bind = 1, Rand = 500},},
	['仙兽吞噬宠物4'] = {{PetKey = "仙兽吞噬宠物4", Level = 1, Bind = 1, Rand = 500},},
	['神兽吞噬宠物4'] = {{PetKey = "神兽吞噬宠物4", Level = 1, Bind = 1, Rand = 500},},
	['魔兽吞噬宠物4'] = {{PetKey = "魔兽吞噬宠物4", Level = 1, Bind = 1, Rand = 500},},
	['圣兽吞噬宠物4'] = {{PetKey = "圣兽吞噬宠物4", Level = 1, Bind = 1, Rand = 500},},
	['元灵吞噬宠物4'] = {{PetKey = "元灵吞噬宠物4", Level = 1, Bind = 1, Rand = 500},},
	['洪荒吞噬宠物4'] = {{PetKey = "洪荒吞噬宠物4", Level = 1, Bind = 1, Rand = 500},},
	['支线巨灵神宝宝'] = {{PetKey = "支线巨灵神宝宝", Level = 1, Bind = 1, Rand = 500},},
	['支线邪毅将军宝宝'] = {{PetKey = "支线邪毅将军宝宝", Level = 1, Bind = 1, Rand = 500},},
	['支线器灵宝宝'] = {{PetKey = "支线器灵宝宝", Level = 1, Bind = 1, Rand = 500},},
	['支线变异瑞兽幼崽宝宝'] = {{PetKey = "支线变异瑞兽幼崽宝宝", Level = 1, Bind = 1, Rand = 500},},
	['支线变异灵木怪宝宝'] = {{PetKey = "支线变异灵木怪宝宝", Level = 1, Bind = 1, Rand = 500},},
	['支线变异赤炎狼宝宝'] = {{PetKey = "支线变异赤炎狼宝宝", Level = 1, Bind = 1, Rand = 500},},
	['支线变异洞花妖宝宝'] = {{PetKey = "支线变异洞花妖宝宝", Level = 1, Bind = 1, Rand = 500},},
	['支线变异素尾白狐宝宝'] = {{PetKey = "支线变异素尾白狐宝宝", Level = 1, Bind = 1, Rand = 500},},
	['支线变异踏火神犀宝宝'] = {{PetKey = "支线变异踏火神犀宝宝", Level = 1, Bind = 1, Rand = 500},},
	['支线变异巨灵神宝宝'] = {{PetKey = "支线变异巨灵神宝宝", Level = 1, Bind = 1, Rand = 500},},
	['支线变异邪毅将军宝宝'] = {{PetKey = "支线变异邪毅将军宝宝", Level = 1, Bind = 1, Rand = 500},},
	['支线变异器灵宝宝'] = {{PetKey = "支线变异器灵宝宝", Level = 1, Bind = 1, Rand = 500},},
	['神兽猪'] = {{PetKey = "神兽猪", Level = 1, Bind = 1, Rand = 500},},
	['神兽鸡'] = {{PetKey = "神兽鸡", Level = 1, Bind = 1, Rand = 500},},
	['神兽狗'] = {{PetKey = "神兽狗", Level = 1, Bind = 1, Rand = 500},},
	['神兽牛'] = {{PetKey = "神兽牛", Level = 1, Bind = 1, Rand = 500},},
	['神兽马'] = {{PetKey = "神兽马", Level = 1, Bind = 1, Rand = 500},},
	['神兽虎'] = {{PetKey = "神兽虎", Level = 1, Bind = 1, Rand = 500},},
	['神兽兔'] = {{PetKey = "神兽兔", Level = 1, Bind = 1, Rand = 500},},
	['神兽羊'] = {{PetKey = "神兽羊", Level = 1, Bind = 1, Rand = 500},},

	['5技能宝宝'] = {{PetKey = "5技能宝宝", Level = 1, Bind = 1, Rand = 500},},
	['6技能宝宝'] = {{PetKey = "5技能宝宝", Level = 1, Bind = 1, Rand = 500},},
	['7技能宝宝'] = {{PetKey = "5技能宝宝", Level = 1, Bind = 1, Rand = 500},},
	['8技能宝宝'] = {{PetKey = "5技能宝宝", Level = 1, Bind = 1, Rand = 500},},
	['9技能宝宝'] = {{PetKey = "5技能宝宝", Level = 1, Bind = 1, Rand = 500},},
	['10技能宝宝'] = {{PetKey = "5技能宝宝", Level = 1, Bind = 1, Rand = 500},},
	['11技能宝宝'] = {{PetKey = "5技能宝宝", Level = 1, Bind = 1, Rand = 500},},
	['12技能宝宝'] = {{PetKey = "5技能宝宝", Level = 1, Bind = 1, Rand = 500},},
	['13技能宝宝'] = {{PetKey = "5技能宝宝", Level = 1, Bind = 1, Rand = 500},},
	['14技能宝宝'] = {{PetKey = "5技能宝宝", Level = 1, Bind = 1, Rand = 500},},
	['15技能宝宝'] = {{PetKey = "5技能宝宝", Level = 1, Bind = 1, Rand = 500},},
	['16技能宝宝'] = {{PetKey = "5技能宝宝", Level = 1, Bind = 1, Rand = 500},},

    --[[
	['宠物礼包1'] = {
        {PetKey = "代理七仙女", Level = 1, Bind = 0, Rand = 500},
        {PetKey = "代理小花仙", Level = 1, Bind = 0, Rand = 500},
		{PetKey = "代理冥焰火凤", Level = 1, Bind = 0, Rand = 500},
		{PetKey = "代理巨灵神", Level = 1, Bind = 0, Rand = 500},
		{PetKey = "代理天神石像", Level = 1, Bind = 0, Rand = 500},
		{PetKey = "代理水帘妖", Level = 1, Bind = 0, Rand = 500},
		{PetKey = "代理水判官", Level = 1, Bind = 0, Rand = 500},
        },
		--]]
}

