--称号物品配置
TitleItemConfig = {} 
	--titleid -称号id
	--typ  -0 限时称号  -1 永久称号
TitleItemConfig.title_List = {
	['称号横行无忌'] = {titleid = 505, typ=0},
	['称号以战止战'] = {titleid = 506, typ=0},
	['称号以武正心'] = {titleid = 507, typ=0},
	['称号胜者为王'] = {titleid = 508, typ=0},
	['称号狠狠一刀'] = {titleid = 511, typ=0},
	['称号稳稳一刀'] = {titleid = 512, typ=0},
	['称号准准一刀'] = {titleid = 513, typ=0},
	['称号终结者']   = {titleid = 514, typ=0},
	['金榜状元']  	 = {titleid = 501, typ=0},
	['金榜榜眼']   	 = {titleid = 502, typ=0},
	['金榜探花']     = {titleid = 503, typ=0},
	['金榜进士']     = {titleid = 504, typ=0},
	['称号鸡中霸王'] = {titleid = 1008, typ=0},
	['君临天下']     = {titleid = 999, typ=1},
	['掌镜使夏冬']   = {titleid = 998, typ=1},
	['超级塞牙人']   = {titleid = 997, typ=1},
	['猴塞雷']   	 = {titleid = 996, typ=1},
	['尊贵号']  	 = {titleid = 995, typ=1},
	['女人'] 		 = {titleid = 994, typ=1},
	['大王的御批']   = {titleid = 993, typ=1},
	['金翅大鹏王幻身咒']= {titleid = 703, typ=1},
	['杨戬幻身咒']   = {titleid = 704, typ=1},
	['猪八戒幻身咒'] = {titleid = 702, typ=1},
	['混世魔王幻身咒']= {titleid = 725, typ=1},
	['孙悟空幻身咒'] = {titleid = 701, typ=1},
	['九灵元圣幻身咒']= {titleid = 729, typ=1},
	['程咬金幻身咒'] = {titleid = 706, typ=1},
	['虎力大仙幻身咒']   = {titleid = 726, typ=1},
	['六耳猕猴幻身咒']   = {titleid = 728, typ=1},
	['牛魔王幻身咒']   = {titleid = 705, typ=1},
	['鹿力大仙幻身咒']   = {titleid = 727, typ=1},
	['太乙天尊幻身咒']   = {titleid = 735, typ=1},
	['龙王幻身咒']   = {titleid = 709, typ=1},
	['水德真君幻身咒']   = {titleid = 710, typ=1},
	['银角大王幻身咒']   = {titleid = 734, typ=1},
	['黄风怪幻身咒']   = {titleid = 732, typ=1},
	['哪吒幻身咒']   = {titleid = 711, typ=1},
	['红孩儿幻身咒']   = {titleid = 740, typ=1},
	['小白龙幻身咒']   = {titleid = 708, typ=1},
	['灵感大王幻身咒']   = {titleid = 730, typ=1},
	['罗刹女幻身咒']   = {titleid = 712, typ=1},
	['黑风怪幻身咒']   = {titleid = 731, typ=1},
	['观音菩萨幻身咒']   = {titleid = 713, typ=1},
	['灵吉菩萨幻身咒']   = {titleid = 737, typ=1},
	['如意真仙幻身咒']   = {titleid = 715, typ=1},
	['地涌夫人幻身咒']   = {titleid = 716, typ=1},
	['唐僧幻身咒']   = {titleid = 714, typ=1},
	['金池长老幻身咒']   = {titleid = 736, typ=1},
	['太上老君幻身咒']   = {titleid = 719, typ=1},
	['沙和尚幻身咒']   = {titleid = 707, typ=1},
	['李靖幻身咒']   = {titleid = 717, typ=1},
	['白骨夫人幻身咒']   = {titleid = 724, typ=1},
	['白无常幻身咒']   = {titleid = 722, typ=1},
	['春十三娘幻身咒']   = {titleid = 718, typ=1},
	['孟婆幻身咒']   = {titleid = 723, typ=1},
	['金角大王幻身咒']   = {titleid = 733, typ=1},
	['黑无常幻身咒']   = {titleid = 721, typ=1},
	['镇元子幻身咒']   = {titleid = 720, typ=1},
	['九尾狐狸幻身咒']   = {titleid = 738, typ=1},
	['羊力大仙幻身咒']   = {titleid = 739, typ=1},
	['神兽猪变身药']   = {titleid = 805, typ=1},
	['神兽鸡变身药']   = {titleid = 806, typ=1},
	['神兽狗变身药']   = {titleid = 807, typ=1},
	['神兽牛变身药']   = {titleid = 808, typ=1},
	['齐天大圣幻身咒']   = {titleid = 741, typ=1},
	['真经小白菜']   = {titleid = 521, typ=1},
	['真经小不懂']   = {titleid = 522, typ=1},
	['真经大虾米']   = {titleid = 523, typ=1},
	['九天战尊']   = {titleid = 524, typ=1},
	['无上战神']   = {titleid = 525, typ=1},
	['嗜血战狂']   	= {titleid = 526, typ=1},
	['恶贯满盈称号']   = {titleid = 531, typ=1},
	['穷凶极恶称号']   = {titleid = 532, typ=1},
	['罪恶滔天称号']   = {titleid = 533, typ=1},
	['除暴安良称号']   = {titleid = 534, typ=1},
	['行侠仗义称号']   = {titleid = 535, typ=1},
	['侠之大者称号']   = {titleid = 536, typ=1},
	['称号官运亨通']   = {titleid = 549, typ=1},
	['称号达官显贵']   = {titleid = 550, typ=1},
	['称号高位重禄']   = {titleid = 551, typ=1},
	['称号官居极品']   = {titleid = 552, typ=1},
	['称号只手遮天']   = {titleid = 553, typ=1},
	['称号十大恶人']   = {titleid = 555, typ=0},
	['称号十大善人']   = {titleid = 556, typ=0},
	['称号元老至尊']   = {titleid = 557, typ=1},
	['真经大玩家']     = {titleid = 558, typ=1},
	['神壕']     = {titleid = 1, typ=1},
	['富可敌国']     = {titleid = 2, typ=1},
	['腰缠万贯']     = {titleid = 3, typ=1},
	['家境殷实']     = {titleid = 4, typ=1},


}
